spring.application.name=animals

file.upload.dir=uploads/
file.upload.posts-dir=uploads/images/posts/
file.upload.avatars-dir=uploads/images/avatars/
file.upload.pets-dir=uploads/images/pets/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.web.resources.static-locations=file:${file.upload.dir}