/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/clinic`; params?: Router.UnknownInputParams; } | { pathname: `/ClinicScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/ValidationMessage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api/service`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/AuthForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/RegistrationForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/Avatar`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/IconButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/Input`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/OrDivider`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/PostCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/SocialButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/StarRating`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/StatItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/TabHeader`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/clinic`; params?: Router.UnknownOutputParams; } | { pathname: `/ClinicScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/registration`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/ValidationMessage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/api/service`; params?: Router.UnknownOutputParams; } | { pathname: `/components/auth/AuthForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/auth/RegistrationForm`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/Avatar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/IconButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/Input`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/OrDivider`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/PostCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/SocialButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/StarRating`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/StatItem`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/TabHeader`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/clinic${`?${string}` | `#${string}` | ''}` | `/ClinicScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/registration${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/components/ui/ValidationMessage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/api/service${`?${string}` | `#${string}` | ''}` | `/components/auth/AuthForm${`?${string}` | `#${string}` | ''}` | `/components/auth/RegistrationForm${`?${string}` | `#${string}` | ''}` | `/components/ui/Avatar${`?${string}` | `#${string}` | ''}` | `/components/ui/Button${`?${string}` | `#${string}` | ''}` | `/components/ui/IconButton${`?${string}` | `#${string}` | ''}` | `/components/ui/Input${`?${string}` | `#${string}` | ''}` | `/components/ui/OrDivider${`?${string}` | `#${string}` | ''}` | `/components/ui/PostCard${`?${string}` | `#${string}` | ''}` | `/components/ui/SocialButton${`?${string}` | `#${string}` | ''}` | `/components/ui/StarRating${`?${string}` | `#${string}` | ''}` | `/components/ui/StatItem${`?${string}` | `#${string}` | ''}` | `/components/ui/TabHeader${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/clinic`; params?: Router.UnknownInputParams; } | { pathname: `/ClinicScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/registration`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/ValidationMessage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api/service`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/AuthForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/auth/RegistrationForm`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/Avatar`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/IconButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/Input`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/OrDivider`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/PostCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/SocialButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/StarRating`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/StatItem`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/TabHeader`; params?: Router.UnknownInputParams; };
    }
  }
}
